### ISSUE TITLE
Test building GHCR on-demand

### ISSUE THREAD

**Issue by grzanka** [yaptide/ui#1051]
Right now Docker image in GHCR is being build for all commits. Lets check if we can spare some CPU by running it on-demand only.

**Comment by grzanka** [comment]
Check triggering on PR comment:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
```
on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
```
